In [5]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

df = pd.read_csv('iriss.txt', sep = ',', header = None)
df.columns = list('ABCDE')
replace_names = {'Iris-setosa':'1','Iris-virginica':'3','Iris-versicolor':'2'}
df.replace(replace_names, regex = True, inplace = True)
features = df.iloc[:,0:4]
cls = df.iloc[:,4]
df.describe()

                A           B           C           D
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000